### PR TITLE
Added changeDevelopmentMode & getAnalyticsDashboard to Zones

### PR DESCRIPTION
**Pull request by MeekLogic**

### CODE REVIEW

**Comment by thellimist** [comment]
Could you run linter?

Thanks

**Comment by IcyApril** [comment]
+1 @thellimist 

@MeekLogic - Thanks for contributing. Could you also make sure you add an associated test for this method in tests/Endpoints/ZonesTest.php ?

Thanks!

**Comment by MeekLogic** [comment]
Just seen this, will add the appropriate test shortly.

**Comment by MeekLogic** [comment]
@IcyApril Thank you very much for pointing me in the right direction.

Threw the PHP CS Fixer PHAR in the directory and ran the command and it worked like magic!

Side note: What environment (OS) are you using? I am using Windows.

**Comment by thellimist** [comment]
We're using Travis CI. https://github.com/cloudflare/cloudflare-php/blob/master/.travis.yml
For style control we're using phpcs-fixer and phpmd. 
And a Makefile https://github.com/cloudflare/cloudflare-php/blob/master/Makefile

Hope this answers your question.

Thanks

**Comment by MeekLogic** [comment]
Thanks @thellimist but I could have gathered that information. What I could not ascertain is what is required of someone to issue those commands within their local environment.

**Comment by IcyApril** [comment]
@MeekLogic Try switching to assertObjectHasAttribute as is the case in testListZones:

```
        $this->assertObjectHasAttribute('result', $result);
        $this->assertObjectHasAttribute('result_info', $result);
        $this->assertEquals("023e105f4ecef8ad9ca31a8372d0c353", $result->result[0]->id);
        $this->assertEquals(1, $result->result_info->page);
```

**Comment by MeekLogic** [comment]
@IcyApril I believe strings, in the curl example he sends date/time values

https://api.cloudflare.com/#zone-analytics-dashboard

**Comment by IcyApril** [comment]
Yeah, that should be fine. We should just make sure the tests are appropriate.

**Comment by MeekLogic** [comment]
Installing PHPMD within VSCode to fix those pesky errors.

**Pull request merged**
