### PR TITLE
Cleanup / fixes

### PR DESCRIPTION
**Pull request by kleisauke**
This PR resolves and cleans a few things. Including:

**Unify code style:**
- Remove unnecessary double quotes (_I can revert this, if you want. The changeset is somewhat big_ 😅).
- Shorten the fully qualified class names.
- Remove redundant parentheses.
- Switch from ` new \stdClass()` to object casting.

**Control flow:**
- Fix loop which doesn't loop.

**Language level migration:**
- All `is_null(...)` calls can be safely replaced with `null === ...` constructs.
- `sizeof(...)` is an alias function. Use `count(...)` instead.

**Performance:**
- Use `$array[] = ...` instead of `array_push(...)`.

**Parameter type:**
- Required parameter type is missing.

**PHPDoc:**
- Argument PHPDoc missing.
- Return type doesn't match.

**Bugs:**
- Fix null pointer exception.
- Class autoloading correctness (file and class name are not identical).

**PHPUnit:**
- `assertCount` should be used instead.

**Unused:**
- Remove arguments which can be safely dropped, as they are identical to the default value.
- Remove unused imports.

**Things that should be considered:**
Instead of a `Makefile` you might look at composer scripts. Something like this:
```json
"scripts": {
    "fix": [
        "php-cs-fixer . fix --config=.php_cs"
    ],
    "lint": [
        "php-cs-fixer . fix --config=.php_cs --dry-run",
        "phpmd src/ text cleancode,codesize,controversial,design,naming,unusedcode",
        "phpmd tests/ text cleancode,codesize,controversial,design,naming,unusedcode"
    ],
    "test": [
        "phpunit --configuration phpunit.xml"
    ]
},
```
This because Linux makefiles doesn't work for Windows users.

### CODE REVIEW

**Comment by thellimist** [comment]
It'd be great if you could split up the changes into multiple commits. It's hard to review effectively 😅

**Comment by kleisauke** [comment]
OK, I've split up the changes into multiple commits. Let me know if something needs to be changed.

**Comment by IcyApril** [comment]
@kleisauke This is awesome! Thanks so much for contributing.

**Comment by MeekLogic** [comment]
I'm totally with switching to Composer to include Windows users!

**Pull request merged**
