### PR TITLE
Major Improvements and modernization

### PR DESCRIPTION
**Pull request by ralphschindler**
This PR probably pulls in many changes others have proposed in the last few months, it effectively attempt to modernize the library. This PR is fully backwards compatible in `src/`

- php 8 compatible
- testing:
    - phpunit 9 preferred (which is php 8 compatible)
    - use createMock()
    - update tests to exist in a dev namespace `Cloudflare\Api\Test`
    - use imports
- remove constructor from interface (better practice, this is Backwards Compatible)
- remove phar files from root
- use specific versions of phpmd and php-cs-fixer
- use `.dist` files for configuration where supported (php-cs and phpunit support these)
- remove dependency on `Makefile` instead using `composer run` scripts (similar in nature to npm run scripts)
- add .gitattributes to reduce what is included in the distributed package on github through packagist

### CODE REVIEW

**Comment by ralphschindler** [comment]
It is worth noting, while this now runs successfully on travis-ci.org, the service will be gone in a few short weeks.

**Comment by loevgaard** [comment]
Can this be reviewed and merged @phily245? :)

**Comment by ralphschindler** [comment]
This branch now has conflicts, also it appears some of the issues originally raised were addressed.

There are likely some outstanding issues, like
- updating to phpunit 9
- removing the Makefile
- removing the ctor from interfaces
- add .gitattributes for cleaner distribution

If you'd like me to clean this up to address those, let me know, I don't mind doing it.

**Comment by ralphschindler** [comment]
Closing, as it appears this project has been abandoned.

**Comment by phily245** [comment]
I do not have permission to merge on this repository

**Pull request closed without merging**
