### PR TITLE
Update to Guzzle 7

### PR DESCRIPTION
**Pull request by keithbrink**
See #141

### CODE REVIEW

**Comment by yellow1912** [comment]
Why not using something like this: "guzzlehttp/guzzle": "^6.0 || ^7.0" to support both versions if the library does not require Guzzle 7 in specific.

**Comment by stayallive** [comment]
I agree with the above, but I would also like to see a Guzzle 7 release if possible (with or without Guzzle 6 support) 👍

**Comment by alexortizrosado** [comment]
Thanks for adding Guzzle 7 support! Any ideas when this will be released (and not only available as dev-master)?

**Comment by aalwash** [comment]
I don't understand, if it was that easy to upgrade tom ^6.2.2 -> ^7.0 without any code changes
Why not making them run together? ^6.2.2 | ^7.0?

Now you're required to upgrade to guzzle7, before you can upgrade the Cloudflare packages to 1.1.7 (from 1.1.3)
Doesn't make any sense that a minor upgrade (1.1.3 -> 1.1.7) has such a huge major guzzle upgrade dependency

**Pull request merged**
