### PR TITLE
Add ipv6 settings management

### PR DESCRIPTION
**Pull request by asafov**

### CODE REVIEW

**Comment by asafov** [comment]
How about merge this PR?

**Comment by asafov** [comment]
??????

**Comment by IcyApril** [comment]
Hi @asafov - Could you please add some unit tests for this functionality? Thanks for contributing!

**Comment by asafov** [comment]
It's problem - i never wrote any unit tests before.

**Comment by asafov** [comment]
So, seems that nobody need this.

**Pull request closed without merging**
