### PR TITLE
Added new TLS & Zone settings Endpoints

### PR DESCRIPTION
**Pull request by pauladams8**
I added the following new endpoints in the TLS.php file and a new ZoneSettings.php file.

- Get HTTPS redirect setting

- Get HTTPS rewrites settings

- Update HTTPS redirect setting

- Update HTTPS rewrites setting

- Get autominify setting

- Get Rocket Loader setting

- Get Always Online setting

- Get email obfuscation setting

- Get hotlink protection setting

- Update autominify setting

- Update Rocket Loader setting

- Update Always Online setting

- Update email obfuscation setting

- Update hotlink protection setting

### CODE REVIEW

**Comment by pauladams8** [comment]
@IcyApril Not sure why this keeps failing the php-cs-fixer, it works on my computer.

Could you have a look, I'm pretty sure I've updated this to PSR-2 compliance.

**Comment by aaronhuisinga** [comment]
@pauladams8 The issue Travis is having is with the variable $js you defined in ZoneSettings.php on line 92.

"Avoid variables with short names like $js. Configured minimum length is 3."

If you change it from $js to $javascript or something along those lines, the build should pass.

**Comment by pauladams8** [comment]
Thanks @aaronhuisinga, I was puzzling over this for a while. Are we ready to merge now?

**Comment by pauladams8** [comment]
@IcyApril ?

**Pull request merged**
